-- Phase 2 of the setup-chat architectural cleanup: attachments become a
-- first-class entity instead of a per-turn payload.
--
-- Before this migration, images were sent inline as base64 with the chat
-- request, parsed once by Sonnet, and discarded. File text (CSV/XLSX/TXT)
-- was inlined into the user message and not persisted at all. The model
-- "remembered" attachments only via the prose it wrote in the same turn,
-- which is fragile - if it gave a one-liner, the description was weak
-- forever.
--
-- After this migration:
--   - Each upload becomes a chat_attachments row, scoped to a conversation.
--   - The raw bytes (or parsed text) are stored in the row.
--   - A short, structured digest is generated by Haiku at upload time and
--     stored alongside.
--   - On the turn the file is uploaded the model sees full content (image
--     bytes or extracted text). On every subsequent turn, only the digest
--     is replayed in the system prompt - ~200 tokens per attachment, vs.
--     re-sending megabytes of base64 every turn.
--
-- This is the "always remembers, never bloats" model the user asked for,
-- equivalent in shape to how Claude.ai handles file uploads internally.

CREATE TABLE IF NOT EXISTS chat_attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  -- Set once the user message that owns this attachment is persisted.
  -- Nullable so an upload can be staged before the chat turn fires
  -- (typical UX: user adds files, then types and sends).
  message_id UUID REFERENCES messages(id) ON DELETE SET NULL,

  filename TEXT NOT NULL,
  -- MIME type, e.g. image/png, image/jpeg, text/csv,
  -- application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  media_type TEXT NOT NULL,
  size_bytes INT NOT NULL,

  -- For images: base64-encoded bytes (without the data: prefix). Sonnet's
  -- vision blocks accept this directly. Capped at ~7M chars (≈5MB binary)
  -- by the upload endpoint.
  raw_base64 TEXT,
  -- For text-shaped files (CSV/XLSX/TXT/MD parsed client-side, PDF parsed
  -- server-side once we add it): the extracted plain-text content. Capped
  -- at 64k chars by the upload endpoint - longer files are head+tail
  -- truncated with a marker between, same approach the legacy file_context
  -- band-aid took.
  extracted_text TEXT,

  -- Structured 2-4 sentence summary written by Haiku at upload time. This
  -- is what gets replayed in the system prompt on every later turn so the
  -- model can reference the attachment without us having to re-send it.
  digest TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Exactly one of (raw_base64, extracted_text) must be populated. An
  -- attachment with neither is meaningless; an attachment with both is
  -- a programming error.
  CONSTRAINT chat_attachments_content_oneof
    CHECK ((raw_base64 IS NOT NULL)::int + (extracted_text IS NOT NULL)::int = 1)
);

CREATE INDEX IF NOT EXISTS idx_chat_attachments_conversation
  ON chat_attachments (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_chat_attachments_message
  ON chat_attachments (message_id) WHERE message_id IS NOT NULL;

ALTER TABLE chat_attachments ENABLE ROW LEVEL SECURITY;

-- Workspace members can read their own attachments. Writes go through the
-- server (service role) so we can run the digest pipeline atomically and
-- enforce the size caps; mirrors how messages are written.
DROP POLICY IF EXISTS "workspace_members_read_chat_attachments" ON chat_attachments;
CREATE POLICY "workspace_members_read_chat_attachments"
  ON chat_attachments
  FOR SELECT
  USING (
    workspace_id IN (
      SELECT workspace_id FROM workspace_members WHERE user_id = auth.uid()
    )
  );
